### ISSUE TITLE
Startup error, unexpected token >

### ISSUE THREAD

**Issue by Yonorov** [keyanzhang/react-atv-img#1]
> react-atv-img [master●] % npm run example
> 
> react-atv-img@0.1.1 example /home/user/apps/dev/react-atv-img
> NODE_ENV=development node devServer.js
> 
> /home/user/apps/dev/react-atv-img/devServer.js:19
> app.get('*', (req, res) => {
>                                      ^
> SyntaxError: Unexpected token >
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:935:3
> 
> npm ERR! react-atv-img@0.1.1 example: `NODE_ENV=development node devServer.js`
> npm ERR! Exit status 8
> npm ERR!
> npm ERR! Failed at the react-atv-img@0.1.1 example script.
> npm ERR! This is most likely a problem with the react-atv-img package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     NODE_ENV=development node devServer.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls react-atv-img
> npm ERR! There is likely additional logging output above.
> npm ERR! System Linux 2.6.32-042stab113.11
> npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "example"
> npm ERR! cwd /home/user/apps/dev/react-atv-img
> npm ERR! node -v v0.10.40
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/user/apps/dev/react-atv-img/npm-debug.log
> npm ERR! not ok code 0

Any ideas on how to fix it ?

**Comment by keyz** [comment]
Hey man,

Thanks for reporting this. Did you `npm install` first? What's your node version?

Thanks.

**Comment by keyz** [comment]
ping.
